using System;
using System.Data;

namespace CooQ.Database
{
  public class DbColumn : DbObject
  {
    private readonly DbType mDbType;
    private readonly Boolean mNullable;
    private Boolean mIsPrimaryKey;
    private Boolean mIsAutoGenerated;
    private readonly Boolean mIsView;
    private string mForeignKeyToTable;
    public string ColumnTypeName { get; set; }
    public string ReturnType { get; set; }

    public DbType DbType
    {
      get
      {
        return this.mDbType;
      }
    }

    public Boolean Nullable
    {
      get
      {
        return this.mNullable;
      }
    }

    public Boolean IsPrimaryKey
    {
      get
      {
        return this.mIsPrimaryKey;
      }
      internal set
      {
        this.mIsPrimaryKey = value;
      }
    }

    public string ForeignKeyToTable
    {
      get
      {
        return this.mForeignKeyToTable;
      }
      internal set
      {
        this.mForeignKeyToTable = value;
      }
    }

    public Boolean IsAutoGenerated
    {
      get
      {
        return this.mIsAutoGenerated;
      }
      internal set
      {
        this.mIsAutoGenerated = value;
      }
    }

    public Boolean IsView
    {
      get
      {
        return this.mIsView;
      }
    }

    public DbColumn(string pName, DbType dbType, Boolean pNullable, Boolean isPrimaryKey, Boolean pIsAutoGenerated, Boolean pIsView)
    {
      this.OriginName = pName;
      this.mDbType = dbType;
      this.mNullable = pNullable;
      this.mIsPrimaryKey = isPrimaryKey;
      this.mIsAutoGenerated = pIsAutoGenerated;
      this.mIsView = pIsView;
    }
  }
}
